# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qGM5xVS1gLrTEFMaFzHhGn-rXij-HaV
"""

import numpy as np
import matplotlib.pyplot as plt

alturas = np.array([[188,160,160,160,160,160,165,159,175],[159,172,174,180,175,175,180,180,180]])

media=np.median(alturas)
media

mediana=np.median(alturas)
mediana

desviacion=np.std(alturas)
desviacion

plt.hist(alturas[0], bins=10, edgecolor='black')
plt.xlabel('Altura (cm)')
plt.ylabel('Frecuencia')
plt.title('Alturas')
plt.show()

plt.imshow(alturas, cmap="terrain")
plt.colorbar(label="alturas")
plt.show()